### PR TITLE
Emma/python class

### PR DESCRIPTION
**Pull request by teresam856**

### CODE REVIEW

**Comment by cmdcolin** [comment]
can you write out high level aims of these PRs?

**Comment by teresam856** [comment]
> can you write out high level aims of these PRs?

These should be moving to this repo https://github.com/teresam856/jbrowse-jupyter
@emmaguo13 is in the process of moving all the work of this PR into the new repo with more context. An initial PR can be found here https://github.com/teresam856/jbrowse-jupyter/pull/8

**Comment by teresam856** [comment]
Closing this PR, work will moved to https://github.com/teresam856/jbrowse-jupyter

**Comment by cmdcolin** [comment]
that is fine but just in general, things like e.g. what is the goal even of transferring this to a new repo? reasoning, benefits, cons, etc. it's just helpful to see the process behind the decisions making

**Comment by teresam856** [comment]
> that is fine but just in general, things like e.g. what is the goal even of transferring this to a new repo? reasoning, benefits, cons, etc. it's just helpful to see the process behind the decisions making

Ahh yes! Will add a note here as well.

Architecture discussion:
Some benefits of moving the API to another repo and making this dash component as a dependency to the jupyter jbrowse package include:
* dash_jbrowse can be reused in other libraries
* reduces the size of dash_jbrowse for those who are not interested in the jupyter functionality
* easier to make updates to either package
* jbrowse jupyter users will only need to download one package to get all the functionality to create jbrowse components and launch them into jupyter cells
* dash_jbrowse was also created from the cookie cutter repo, so trying to differentiate the python jupyter package with the React  dash_jbrowse package can be a little confusing for contributors and maintainers.

**Pull request closed without merging**
